FIND_PATH(SOPHUS_INCLUDE_DIRS sophus ${PROJECT_SOURCE_DIR})
#message(${PROJECT_SOURCE_DIR})
FIND_LIBRARY(SOPHUS_LIBRARIES NAMES sophus PATH ${PROJECT_SOURCE_DIR})

IF(SOPHUS_INCLUDE_DIRS)
    SET(SOPHUS_INCLUDE_DIRS TRUE)
    message(SOPHUS_INCLUDE_DIRS found!)
ENDIF(SOPHUS_INCLUDE_DIRS)

IF(SOPHUS_LIBRARY)
    SET(SOPHUS_LIBRARY_FOUND TRUE)
    message(SOPHUS_LIBRARY found!)
ENDIF(SOPHUS_LIBRARY)
